crud/urls.py
from django.urls import re_path, path
from app import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [  
    path('', views.CalendarView.as_view(), name='adminCalendar'),
    re_path(r'^adminCalendar', views.CalendarView.as_view(), name='adminCalendar'),
    re_path(r'^userCalendar$', views.CalendarViewEmp.as_view(), name='userCalendar'),
    re_path(r'^event/new$', views.event, name='event_new'),
    re_path(r'^event/delete/(?P<event_id>\d+)/$', views.delete_event, name='event_delete'),
    re_path(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.urls import reverse
 
class Event(models.Model): 
    CATEGORY_CHOICES = [ ('Birthday', 'Birthday'), ('Public Holiday', 'Public Holiday'), ('Event', 'Event'), ('Others', 'Others'),]
    visibility = models.BooleanField(default=False ) 
    title = models.CharField(max_length=200)
    description = models.TextField()
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES)
    date = models.DateField()
    @property
    def get_event_description(self):
          
        des =Event.objects.get(id = self.id,description = self.description) 
        try:
            des =Event.objects.get(id = self.id,description = self.description)
            return des.description
        except:
            return False
     
    @property
    def get_html_url(self):
        url = reverse('event_edit', args=(self.id,))
        return f'<a href="{url}"> <span class ="options" style="  margin-top:1px;color:#707070;  " > <img class="img1"style="width:20px; height:20px;" src="../static/assets/img/edit.png" alt="edit"/> </span></a><br> '
    @property
    def deleteEvent(self):  
        urls = reverse('event_delete', args=(self.id,))
        return f'<br><a href="{urls}"> <span class ="options"id = "options"  > <img class="img2"style="width:20px; margin-top:10px;color:#707070;"src="../static/assets/img/delete.png" alt="delete"/> </span></a>'
        # return f'<br><button id="primaryButton{cot}" href="{urls}" ></button>' 
        # return f'<br> <a data-bs-toggle="modal" data-bs-target="#sureModal"> <span class ="options" style="  margin-top:20px;color:#707070;" > <img class="img2"style="width:20px; margin-top:10px;color:#707070;"src="../static/assets/img/delete.png" alt="delete"/> </span></a><div class="modal fade" id="sureModal" tabindex="-1" aria-labelledby="sureModalLabel" aria-hidden="true"> <div class="modal-dialog"> <div class="modal-content"> <div class="modal-header"><h5 class="modal-title" id="sureModalLabel">Are you Sure?</h5></div> <div class="modal-footer"><button type="button" style="background-color:red;" class="btn btn-danger" data-bs-dismiss="modal">No</button><a href="{urls}" class="btn btn-primary">Yes</a></div></div></div></div>'
        # return f'<br><button hidden id="primaryButton" href="{urls}"></button><a data-bs-toggle="modal" data-bs-target="#sureModal"> <span class ="options" style="  margin-top:20px;color:#707070;" > <img class="img2"style="width:20px; margin-top:10px;color:#707070;"src="../static/assets/img/delete.png" alt="delete"/> </span></a><div class="modal fade" id="sureModal" tabindex="-1" aria-labelledby="sureModalLabel" aria-hidden="true"> <div class="modal-dialog"> <div class="modal-content"> <div class="modal-header"><h5 class="modal-title" id="sureModalLabel">Are you Sure?</h5></div> <div class="modal-footer"><button type="button" style="background-color:red;" class="btn btn-danger" data-bs-dismiss="modal">No</button><button type="button" id='"secondaryButton"' class="btn btn-primary" onclick="document.getElementById("primaryButton").click()">Yes</button></div></div></div></div>'
    


        

app/forms.py
from django import forms  
from .models import *
from django.forms import ModelForm, DateInput

class DateInput(forms.DateInput):
    input_type = 'date'
         
          
choice = [('True','Admin Only   '),('False', 'Both')]
class EventForm(ModelForm):
  
  class Meta:

    model = Event
    # datetime-local is a HTML5 input type, format to make date time show on fields
    widgets = {
      'date': DateInput(format='%Y-%m-%d'),
      'visibility' : forms.RadioSelect(choices=choice)
    }
    fields = '__all__'    

app/views.py
from django.shortcuts import render, redirect ,HttpResponse ,  HttpResponseRedirect, get_object_or_404
from django.contrib import messages
from .models import *
from .forms import *

# from .models import Addemployee, Leave_App, Event, Admin_Login
# from .forms import AddemployeeForm, Admin_LoginForm, EventForm, Leave_AppForm 
from django.conf import settings
from django.core.mail import send_mail 
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from datetime import datetime
from datetime import date
import os 
from django.db import connection
from django.db.models import Count 
from django.urls import reverse
from .utils import Calendar, Eventcal
import calendar
from django.utils.safestring import mark_safe
from datetime import datetime, timedelta
from django.views import generic
 
class CalendarView(generic.ListView):
    
    model = Event
    template_name = 'adminCalendar.html'
     
    def get_context_data(self, **kwargs):
        
        context = super().get_context_data(**kwargs)

        # use today's date for the calendar
        today = str(get_date(self.request.GET.get('day', None)))
        today_year, today_month, today_date = (int(x) for x in today.split('-')) 
        adminStatus = True
        d = get_date(self.request.GET.get('month', None))
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        cal = Calendar(d.year, d.month, today_date, today_month, today_year, adminStatus)
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        event = Eventcal(d.year, d.month, adminStatus)
        html_event = event.formatmonth(withyear=True)
        context['event'] = mark_safe(html_event)
         
        return context
    
class CalendarViewEmp(generic.ListView):
    
    model = Event
    template_name = 'userCalendar.html'
    
     
    def get_context_data(self, **kwargs): 
        context = super().get_context_data(**kwargs)

        # use today's date for the calendar
        today = str(get_date(self.request.GET.get('day', None))) 
        today_year, today_month, today_date = (int(x) for x in today.split('-')) 
        
        d = get_date(self.request.GET.get('month', None))
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        adminStatus = False
        cal = Calendar(d.year, d.month, today_date, today_month, today_year, adminStatus)
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        event = Eventcal(d.year, d.month, adminStatus)
        html_event = event.formatmonth(withyear=True)
        context['event'] = mark_safe(html_event) 
        return context
    

def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month

def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month

def get_date(req_day):
    if req_day:
        year, month = (int(x) for x in req_day.split('-'))
        return date(year, month, day=1)
    return date.today()


# Event add
def event(request, event_id=None):
    instance = Event()
    if event_id:
        instance = get_object_or_404(Event, pk=event_id)
    else:
        instance = Event()
    
    form = EventForm(request.POST or None, instance=instance)
    if request.POST and form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('adminCalendar'))
    return render(request, 'event.html', {'form': form})

def delete_event(request, event_id):
    instance = Event()
    if event_id:
        instance = get_object_or_404(Event, pk=event_id)
    else:
        instance = Event()
    instance.delete()
    return redirect('adminCalendar')


 

app/templates/adminCalendar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Sversity is the online edu. Tech division of Apcosys Private Limited and Apcosys is a software development and consultancy company with headquarter in Bangalore, India. Sversity online learning destination, offering high-quality courses from the world's best universities and institutions to learners everywhere. In the age of internet, do we really need to spend huge amount on getting degrees? One can equally quench his third for knowledge by joining online classes.">
    <title>Leapss - Leave Management System</title>
    {% load static %}
    <link href="{% static 'assets\css\admin.css' %}" rel="stylesheet">
    <link href="{% static 'assets\css\calendar.css' %}" rel="stylesheet">
 
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
 
    <!-- Google Icon -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,200,0,0" />

</head>
<body id="body-pd">
  <nav class="navbar border-bottom navbar-default">
  <div class="container-fluid justify-content-between">
    <div class="navbar-header">
      <a class="navbar-brand">Customized Event Calendar</a>
    </div> 
    <div>
      <a class="btn btn-info navbar-btn" href="{% url 'userCalendar' %}">User View</a>
    </div>
  </div>
</nav> 
    <div class="d-flex" id="wrapper">  
            <section class="section container bg-white rounded dashboard"> 
                <div class=" cal empInfo">
                    <div class="clear justify-content-around row">
                      <div class="col-md-1">
                        <a class="btn left" href="/adminCalendar?{{ prev_month }}"> 
                          <span style="color:#5b5b5b; margin-top: 5px; left: 420px;width: 12px;height: 20px;" class="material-symbols-outlined">
                          arrow_back_ios
                          </span>  </a>
                      </div>
                      <div class="col-md-6"></div>
                      <div class="col-md-1">
                        <a class="btn right" href="/adminCalendar?{{ next_month }}">
                          <span style="color:#5b5b5b;margin-top: 5px;" class="material-symbols-outlined">
                          arrow_forward_ios
                          </span>  </a>
                      </div>
                      <div class="col-md-4"></div>
                    </div>
                  
                  <div class="row" style="background-color:#fff;">
                    <div class="col-md-8">
                      {{ calendar }}
                    </div>
                      <div class="col-md-4  event">
                        <div style="text-align:center">
                          <div class="row indicators">
                            <div class="col-md-6">
                              <ul>
                                <li style="color: #009eff;"><span style="color: #0f0f0f;">Events</span></li>
                                <li style="color: #eb5353;"><span style="color: #0f0f0f;">Holidays</span></li>
                              </ul>
                            </div>
                            <div class="col-md-6">
                              <ul>
                                <li style="color: #ffc149;"><span style="color: #0f0f0f;">Birthdays</span></li>
                                <li style="color: #808080;"><span style="color: #0f0f0f;">Others</span></li>
                              </ul>
                            </div>
                          </div>
                          <div class="row">
                            <div class="col-md-6 alive">
                              <a class="btn  eventHeader" href="{% url 'event_new' %}"> Add Event</a>

                            </div>
                            <div class="col-md-6 ">
                              <a class="btn dead deleteEve  eventHeader" onclick="disdel()"> Delete Event</a>
                              <a style="display: none;text-decoration: none;"btn class="deleteEve ded eventHeader" onclick="candel()"> Cancel</a>

                            </div>
                          </div>
                          
                        </div> 
                        <div class="eve "> 
                          {{ event }}
                        </div>  
                        
                      </div> 
                      </div>
                  </div> 
            </section> 
          </div>
            <div id="footer">
              <p class="footertext"> &copy; Copyright <script>document.write(new Date().getFullYear())</script> | <a href="https://krishnashahu.com.np" target="_blank"> Krishna Shahu</a> | All Rights Reserved</p> 
            </div> 
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
     
    <script src="{% static 'assets\js\main.js' %}"></script>
      
</body>
</html>

app/templates/event.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Event</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <style>
            body{
                display: flex;
                align-items: center;
                justify-content: center;
            }
            .clearfix{
                display: flex;
                justify-content: center;
                align-items: center;
                padding: 5%;
                font-size: 22px;
                font-weight: 600;
            }
            .clearfix a{
                color: #fff;
                text-decoration: none;
            }
            .clearfix{
                background-color: #009eff;
                border-radius: 4px;
                color: #fff;
                text-align: center;
                padding: 5%;
                font-weight: 600;
                border: 1px solid #009eff;
                border-bottom-left-radius: 0px;
                border-bottom-right-radius: 0px;
            }
            
            .container{ 
                box-shadow: 0 5px 30px 0 rgba(82, 63, 105, 0.2);
            }
            form{
                padding: 0% 10%;
                text-align: left;
                color: #009eff;
            }
            .form-table input, .form-table select {
                border: 1px solid #aaa;
                outline: none;
                padding: 8px;
                box-sizing: border-box;
                border-radius: 2px;
                margin: 2%;
                width: 100%;
            }
            .form-table textarea {
                border: 1px solid #aaa;
                outline: none;
                padding: 8px;
                box-sizing: border-box;
                border-radius: 2px;
                margin: 2%;
                height: 100px;
                width: 100%;
            }
            button{
                background-color: #009eff;
                margin: 2%;
                padding: 2.2%;
                width: 46%;
                border-radius: 4px;
                border: none;
                color: #fff;
            }
            td a{
                background-color: #009eff;
                text-decoration: none;
                padding: 2.5% 18%;
                width: 100%;
                font-size: 14px;
                border-radius: 4px;
                border: none;
                color: #fff;
            }
            button:hover{
                background-color: #fff;
                border: 1px solid #009eff;
                color: #009eff;
            }
            #id_visibility_0{
                position: relative;
                top: 23px;
            }
            #id_visibility_1{
                position: relative;
                top: 21px;
            }
            #id_visibility{
                padding-top: 5%;
                padding-left: 3%;
            }
            #footer{
              background-color: #009eff;
              color: #fff;
              padding: 2%;
              border-bottom-left-radius: 5px;
              border-bottom-right-radius: 5px;
            }
            .footertext{
              text-align: center ;
              margin: 0%;
              background-color: #009eff;
            }
            .footertext a{
              color: #fff;
            }
        </style>
    </head>
    <body>
        
        <div class="container">
            <div class="clearfix">
                <a class="btn btn-info left" href="javascript:void(0);">Customized Django Event Calendar</a>
            </div>
              <hr width="80%">  
              <h2 style="text-align: center; color: #009eff;">Add Event</h2>
              <hr width="80%">  
            <form method="post">
                {% csrf_token %}
                <table class="form form-table">
                    {{ form }} 

                    <tr><td style="text-align: center;" colspan="4"><hr><button type="submit" class="btn btn-info right"> Submit </button><a class="btn btn-info left" href="/adminCalendar">Cancel</a><hr></td></tr>
                    
                </table>
            </form>
            <div id="footer">
              <p class="footertext"> &copy; Copyright <script>document.write(new Date().getFullYear())</script> | <a href="https://krishnashahu.com.np" target="_blank"> Krishna Shahu</a> | All Rights Reserved</p> 
            </div> 
            
        </div>
        <script >
            var today = new Date();
            var dd = String(today.getDate()).padStart(2, '0');
            var mm = String(today.getMonth() + 1).padStart(2, '0');
            var yyyy = today.getFullYear();
    
            today = yyyy + '-' + mm + '-' + dd;
            $('#id_date').attr('min',today);
        </script>
        <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    </body>
</html>

app/templates/userCalendar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Sversity is the online edu. Tech division of Apcosys Private Limited and Apcosys is a software development and consultancy company with headquarter in Bangalore, India. Sversity online learning destination, offering high-quality courses from the world's best universities and institutions to learners everywhere. In the age of internet, do we really need to spend huge amount on getting degrees? One can equally quench his third for knowledge by joining online classes.">
    <title>Leapss - Leave Management System</title>
    {% load static %}
    <link href="{% static 'assets\css\admin.css' %}" rel="stylesheet">
    <link href="{% static 'assets\css\calendar.css' %}" rel="stylesheet">
 
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
 
    <!-- Google Icon -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,200,0,0" />
    <style>
      .options{
        display: none;
      }
    </style>
</head>
<body id="body-pd">  
  <nav class="navbar border-bottom navbar-default">
    <div class="container-fluid justify-content-between">
      <div class="navbar-header">
        <a class="navbar-brand">Customized Event Calendar</a>
      </div> 
      <div>
        <a class="btn btn-info navbar-btn" href="{% url 'adminCalendar' %}">Admin View</a>
      </div>
    </div>
  </nav> 
            <section class="section container  pageClass bg-white rounded dashboard"> 
                <div class="empInfo cal">
                    <div class="clear justify-content-around row">  
                        <div class="col-md-1">
                          <a class="btn left" href="/userCalendar?{{ prev_month }}"> 
                            <span style="color:#5b5b5b; margin-top: 5px; left: 420px;width: 12px;height: 20px;" class="material-symbols-outlined">
                            arrow_back_ios
                            </span>  </a>
                        </div>
                        <div class="col-md-6"></div>
                        <div class="col-md-1">
                          <a class="btn right" href="/userCalendar?{{ next_month }}">
                            <span style="color:#5b5b5b;margin-top: 5px;" class="material-symbols-outlined">
                            arrow_forward_ios
                            </span>  </a>
                        </div>
                        <div class="col-md-4"></div>
                    </div>
                  
                  <div class="row" style="background-color:#fff;">
                    <div class="col-md-8">
                      {{ calendar }}
                    </div>
                      <div class="col-md-4  event">
                        <div style="text-align:center">
                          <div class="row indicators">
                            <div class="col-md-6">
                              <ul>
                                <li style="color: #009eff;"><span style="color: #0f0f0f;">Events</span></li>
                                <li style="color: #eb5353;"><span style="color: #0f0f0f;">Holidays</span></li>
                              </ul>
                            </div>
                            <div class="col-md-6">
                              <ul>
                                <li style="color: #ffc149;"><span style="color: #0f0f0f;">Birthdays</span></li>
                                <li style="color: #808080;"><span style="color: #0f0f0f;">Others</span></li>
                              </ul>
                            </div>
                          </div>
                          <a class="btn  evenHeader"  disabled aria-disabled="true"> Events</a>
                          
                        </div>
                        <div class="eve">{{ event }}</div>
                        
                      </div> 
                      </div>
                  </div> 
              </section> 
              <div id="footer">
                <p class="footertext"> &copy; Copyright <script>document.write(new Date().getFullYear())</script> | <a href="https://krishnashahu.com.np" target="_blank"> Krishna Shahu</a> | All Rights Reserved</p> 
              </div> 
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
     
    <script src="{% static 'assets\js\main.js' %}"></script>

</body>
</html>